version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/Inno-Doctor
    ports:
      - 8000:8000
    image: inno-dcotor:django
    container_name: django_container

    command: python manage.py runserver 0.0.0.0:8000

